### ISSUE TITLE
display.py doesn't finish cleanly

### ISSUE THREAD

**Issue by Matbbastos** [gipsa-lab-uav/trajectory-control#1]
Hi,

When running the trajectory_control node, the display.py script can be also launched to provide data during the flight, however it is not essential. Currently, when the plot window is closed, it escalates some errors related to the "killing" of the display process, those rise up to the terminal messages.

The messages are as following:
```bash
Traceback (most recent call last):
  File "/home/bruhnsbm/catkin_ws/src/trajectory_control/scripts/display.py", line 238, in <module>
    d.start()
  File "/home/bruhnsbm/catkin_ws/src/trajectory_control/scripts/display.py", line 231, in start
    fig.canvas.draw()
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 304, in draw
    FigureCanvasAgg.draw(self)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 433, in draw
    toolbar.set_cursor(toolbar._lastCursor)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 692, in set_cursor
    self.window.configure(cursor=cursord[cursor])
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1339, in configure
    return self._configure('configure', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1330, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name "."
[display_node-8] process has died [pid 17985, exit code 1, cmd /home/bruhnsbm/catkin_ws/src/trajectory_control/scripts/display.py __name:=display_node __log:=/home/bruhnsbm/.ros/log/22b99f12-1a62-11ea-be59-1803732d6e8a/display_node-8.log].
log file: /home/bruhnsbm/.ros/log/22b99f12-1a62-11ea-be59-1803732d6e8a/display_node-8*.log
```

Probably wrapping the initialization of the node object might solve the issue.

**Comment by SaAPro** [comment]
Fix in 081f7ffd68621dee59e2805d9cb265031a3169d4 on dev
